### ISSUE TITLE
Affichage des lignes de commandes

### ISSUE THREAD

**Issue by flotho** [noemis-fr/custom#1]
Bonjour @legalsylvain ,

J'ai un souci chez Noemis que Grégory Bayle me dit avoir déjà été résolu par tes soins et je ne trouve pas trace dans les logs gits. Cela concerne l'ordre d'affichage des lignes dans les bons de commande/ devis saisis par les commerciaux. Ils perdent l'ordre d'affichage  suite à des déplacements de lignes. Aurais tu souvenir d'une intervention spéciale de ta part?

Merci d'avance du coup de pouce et du retour.

**Comment by legalsylvain** [comment]
Hello, non désolé. pas d'avis sur le sujet.

bon courage !

**Comment by flotho** [comment]
Merci @legalsylvain 
A bientôt sur d'autres sujets
